# Site settings
timezone: Asia/Jakarta
encoding: utf-8
author: Bagus18
title: Dibatasi Imajinasi
email: bagus@teknik.io
description: Limited by Imagination
baseurl: ""
url: "https://bagus18.github.io

permalink: note/:categories/:title.md
github_username:  bagus18
markdown: kramdown

collections:
    notes:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: "_post"
      type: "article"
    values:
      layout: "post"
      author: "Bagus18"
      image: https://avatars0.githubusercontent.com/u/18557160

gems:
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-sitemap

plugins:
  - jemoji
  
#branch: gh-pages
