# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
timezone: Asia/Jakarta
encoding: utf-8
author: Bagus18
title: Dibatasi Imajinasi
email: bagus18@yandex.com
img: https://avatars0.githubusercontent.com/u/18557160
bagus18: https://scontent-sit4-1.cdninstagram.com/t51.2885-15/e35/15535345_1616912278618409_3317526163559022592_n.jpg
description: > # this means to ignore newlines until "baseurl:"
  Aku sudah pernah merasakan semua kepahitan dalam hidup, 
  dan yang paling pahit adalah berharap kepada manusia. 
  Ali Bin Abi Thalib.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bagus18.github.io" # the base hostname & protocol for your site
permalink: note/:categories/:title.md
twitter_username: bagusak18
github_username:  bagus18

# Build settings
markdown: kramdown

defaults:
  - scope:
      path: "_post"
      type: "article"
    values:
      layout: "post"
      author: "Bagus18"
      image: https://avatars0.githubusercontent.com/u/18557160
      author: "Bagus18"
gems:
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-sitemap

plugins:
  - jemoji
  
#branch: gh-pages
